### ISSUE TITLE
Prohibit Node from changing `params.yaml` or `zntrack.json` during `run`

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#221]
After #176 there are no checks in place if `zn.outs` are written outside the run method or `zntrack.json` / `params.yaml` are changed during the run method. This can cause a loop of always running the Node after the script is rewritten because the inputs are overwritten.

# TODOs
- [x] write (failing) tests that the `zntrack.json` and `params.yaml` can not be changed in the run (change `self.path` to str for example)
- [ ] write (failing) tests that the `zn.<option>` files are changed outside a `run` method of the node. This might require a `run=True` in the `load` method to avoid some `pre-run` code hack.
- [ ] fix the tests
- [ ] Log a warning if the context of a Node is being accessed when the Node is not loaded.
