### ISSUE TITLE
0.6.0 TODOs

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#524]
# TODOs
- [x] add ZnFlow package
- [x] add `$nwd$`
- [x] fix lazy loading
- [x] fix jupyter support
- [ ] add legacy tests back
- [ ] test if `zn.outs` or `zn.metrics` are not set in the `run` method.
- [x] test `zntrack.Project`
- [ ] znflow getitem support
- [x] rename `get_affected_files` to `get_files`
- [ ] add `get_deps_if_node` utils
- [ ] solve issue if a Node is being loaded in between two `project.run` calls.
- [x] do not allow outs to be set in the ``__init__``
- [ ] eager does not work with `meta.Text`
- [ ] add operating directory
- [x] rename `from_rev(origin=)` to `from_rev(remote=)` to be compliant with `git remote add`
- [ ] fix issue if two experiments change parameters of different nodes
- [ ] move graph to `project.graph`
- [ ] have `with Project(run=True, save=True)` to avoid a closing `project.run()` 
- [ ] add warning, if force is required? Only write zntrack / params.yaml if a Node is being changed? Do not default to `--force`.
- [ ] automatically name a Node. e.g. if a Node occurs multiple times, name it `WriteOuts` and then `WriteOuts_1`, ... ? This should be a keyword option
